# Generated by Django 3.0.4 on 2020-03-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('paymentNum', models.CharField(max_length=100)),
                ('yearTotal', models.CharField(max_length=100)),
                ('lastGift', models.CharField(max_length=100)),
                ('lastGiftDate', models.CharField(max_length=100)),
                ('nextLastGift', models.CharField(max_length=100)),
                ('nextLastGiftDate', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('recentCallDate', models.CharField(max_length=100)),
                ('steward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='donor_app.Steward')),
            ],
        ),
    ]
