# Generated by Django 3.0.4 on 2020-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='recentCallDate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
