# Generated by Django 3.0.4 on 2020-03-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0002_auto_20200306_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='recentCallDate',
        ),
    ]
