# Generated by Django 3.0.4 on 2020-03-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0003_remove_donor_recentcalldate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='orgName',
            new_name='orgname',
        ),
    ]
