# Generated by Django 3.0.4 on 2020-03-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0004_auto_20200306_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='lastGift',
            new_name='lastgift',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='lastGiftDate',
            new_name='lastgiftdate',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='nextLastGift',
            new_name='nextlastgift',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='nextLastGiftDate',
            new_name='nextlastgiftdate',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='paymentNum',
            new_name='paymentnum',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='yearTotal',
            new_name='yeartotal',
        ),
    ]
