# Generated by Django 3.0.4 on 2020-03-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0005_auto_20200306_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='botSteward',
            field=models.CharField(default='Gretchen Bond', max_length=100),
        ),
    ]
