# Generated by Django 3.0.4 on 2020-03-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0008_auto_20200306_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
