# Generated by Django 3.0.4 on 2020-03-06 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor_app', '0010_auto_20200306_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='steward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='donor_app.Profile'),
        ),
        migrations.DeleteModel(
            name='Steward',
        ),
    ]
